name: real_estate
description: Client Real Estate App Project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  google_fonts: ^1.1.0
  firebase_auth: ^0.18.1+2
  share: ^0.6.5+2
  url_launcher: ^5.7.2
  modal_progress_hud: ^0.1.3
  chips_choice: ^2.0.1
  firebase_core: ^0.5.0+1
  firebase_storage: ^4.0.1
  file_picker: ^1.13.3
  http: ^0.12.2
  provider: ^4.3.2+2
  flappy_search_bar: ^1.7.2
  flutter_launcher_icons: ^0.8.1


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/playstore.png"


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
  #   - images/a_dot_ham.jpeg
